import vite from '../assets/projects-image/vite.png';
import aiirolafin from '../assets/projects-image/aiirolafin.png';
import colorPalette from '../assets/projects-image/colorpallate.png';
import Genzbank from '../assets/projects-image/genzbank.png';
import thebakery from '../assets/projects-image/thebakery.png';
import vintage from '../assets/projects-image/vintage.png';

const projects = [
    {
        id: 1,
        img: vite,
        title: 'vite-clone',
        desc: `A Vitejs Website Clone Built with`,
        tech: ' React, Context API, CSS.',
        role: 'Front-End',
        live: '',
        web: '',
        // github: 'https://github.com/SharafaCode/vite-clone',
        // webgit: 'www.github.com/SharafaCode/vite-clone',
        
    },
    {
        id: 2,
        img: aiirolafin,
        title: 'aiirolafin',
        desc: 'A Website Estate Management Landing Page Built with',
        tech: 'JavaScript and Sass.',
        role: 'Front-End',
        live: 'https://aiirolafin.netlify.app/',
        web: 'www.aiirolafin.netlify.app',
        // github: 'https://github.com/SharafaCode/RealEstate',
        // webgit: 'www.github.com/SharafaCode/RealEstate',
    },
    {
        id: 3,
        img: colorPalette,
        title: 'color-palettes',
        desc: 'A Color Palette Website with Values-js Data Implemented Built with ',
        tech: 'Reactjs and Valuejs for(data).',
        role: 'Front-End',
        live: 'https://color-paletterxzy.netlify.app/',
        web: 'www.color-paletterxzy.netlify.app',
        // github: 'https://github.com/SharafaCode/Color-Palette',
        // webgit: 'www.github.com/SharafaCode/Color-Palette',
        
    },
    {
        id: 4,
        img: Genzbank,
        title: 'genzbank',
        desc: 'A Payment Banking Method Landing Page Built with',
        tech: 'Reactjs and Css.',
        role: 'Front-End',
        live: 'https://genzbank.netlify.app/',
        web: 'www.genzbank.netlify.app',
        // github: 'https://github.com/SharafaCode/GenZBank',
        // webgit: 'www.github.com/SharafaCode/GenZBank',
    },
    {
        id: 5,
        img: thebakery,
        title: 'thebakery',
        desc: 'Landing Page Food Website built with Real, ',
        tech:'Reactjs, Css, and ContextApi',
        role: 'Front-End',
        live: 'https://thebake.netlify.app/',
        web: 'www.thebake.netlify.app',
        // github: 'https://github.com/SharafaCode/TheBakery',
        // webgit: 'www.github.com/SharafaCode/TheBakery',
    },
    {
        id: 6,
        img: vintage,
        title: 'vintage',
        desc: 'An E-commencer Website Built with.',
        tech: 'Swipperjs library, JavaScript and Sass.',
        role: 'Front-End',
        live: 'https://vintagex.netlify.app/',
        web: 'www.vintagex.netlify.app',
        // github: 'https://github.com/SharafaCode/Vintage',
        // webgit: 'www.github.com/SharafaCode/Vintage',
    },
    {
        id: 7,
        img: vintage,
        title: 'yello',
        desc: 'An E-commencer Website Built with Swipperjs library, JavaScript and Sass. ',
        tech: 'Swipperjs library, JavaScript and Sass.',
        role: 'Front-End',
        live: 'https://vintagex.netlify.app/',
        web: 'www.vintagex.netlify.app',
        // github: 'https://github.com/SharafaCode/Vintage',
        // webgit: 'www.github.com/SharafaCode/Vintage',
    },
    {
        id: 8,
        img: vintage,
        title: 'good',
        desc: 'An E-commencer Website Built with Swipperjs library, JavaScript and Sass. ',
        tech: 'Swipperjs library, JavaScript and Sass.',
        role: 'Front-End',
        live: 'https://vintagex.netlify.app/',
        web: 'www.vintagex.netlify.app',
        // github: 'https://github.com/SharafaCode/Vintage',
        // webgit: 'www.github.com/SharafaCode/Vintage',
    },
    {
        id: 9,
        img: vintage,
        title: 'hello',
        desc: 'An E-commencer Website Built with Swipperjs library, JavaScript and Sass. ',
        tech: 'Swipperjs library, JavaScript and Sass.',
        role: 'Front-End',
        live: 'https://vintagex.netlify.app/',
        web: 'www.vintagex.netlify.app',
        // github: 'https://github.com/SharafaCode/Vintage',
        // webgit: 'www.github.com/SharafaCode/Vintage',
    },
];


export default projects;